name: DINOv2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - umap-learn
  - plotly
  - h5py
  - numpy
  - tqdm
  - pip
  - pip:
      - h5py
