data_param:
  data_path: '/Users/tomw/Documents/MVA/Internship/Cambridge/Samia/Synister_NeurotransmitterPrediction' 
  dataset_proportions: [0.8, 0.1, 0.2]
  batch_sizes: [200,100,100]
  num_workers:  

utils_param:
